//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinkingCat.HelperLibs.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class ResourcePath : global::System.Configuration.ApplicationSettingsBase
    {

        private static ResourcePath defaultInstance = ((ResourcePath)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ResourcePath())));

        public static ResourcePath Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Resources\\crosshair.cur")]
        public string regionCapturCrosshair
        {
            get
            {
                return ((string)(this["regionCapturCrosshair"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Settings\\PathSettings.config")]
        public string pathSettingsFile
        {
            get
            {
                return ((string)(this["pathSettingsFile"]));
            }
        }
    }
}
