//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinkingCat.HelperLibs.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig")]
        public string configFolderPath
        {
            get
            {
                return ((string)(this["configFolderPath"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Logs")]
        public string logFolderPath
        {
            get
            {
                return ((string)(this["logFolderPath"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Resources")]
        public string resourceFolderPath
        {
            get
            {
                return ((string)(this["resourceFolderPath"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Settings")]
        public string settingsFolderPath
        {
            get
            {
                return ((string)(this["settingsFolderPath"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Screenshots")]
        public string screenshotFolderPathDefault
        {
            get
            {
                return ((string)(this["screenshotFolderPathDefault"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Settings\\MainForm.config")]
        public string mainFormSettings
        {
            get
            {
                return ((string)(this["mainFormSettings"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Settings\\MainFormStyles.config")]
        public string mainFormStyles
        {
            get
            {
                return ((string)(this["mainFormStyles"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Settings\\Hotkeys.config")]
        public string hotkeySettings
        {
            get
            {
                return ((string)(this["hotkeySettings"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Settings\\RegionCapture.config")]
        public string regionCaptureSettings
        {
            get
            {
                return ((string)(this["regionCaptureSettings"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Settings\\RegionCaptureStyles.config")]
        public string regionCaptureStyles
        {
            get
            {
                return ((string)(this["regionCaptureStyles"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Settings\\ClipStyles.config")]
        public string clipStyles
        {
            get
            {
                return ((string)(this["clipStyles"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Settings\\Clipboard.config")]
        public string clipboardSettings
        {
            get
            {
                return ((string)(this["clipboardSettings"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Settings\\LoadedItems")]
        public string LoadedItems
        {
            get
            {
                return ((string)(this["LoadedItems"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\AppConfig\\Settings\\MiscSettings.config")]
        public string MiscSettings
        {
            get
            {
                return ((string)(this["MiscSettings"]));
            }
        }
    }
}
